### ISSUE TITLE
Long press event not sent when both longpress and repeat is active

### ISSUE THREAD

**Issue by Extrunder** [MajicDesigns/MD_KeySwitch#2]
This code should fix this issue:
in switch case S_LPRESS.
`} else if (bitRead(_enableFlags, REPEAT_ENABLE) && bitRead(_enableFlags, LONGPRESS_ENABLE)) {
    k = KS_LONGPRESS;
    _state = S_REPEAT;
    break;
}`

**Comment by MajicDesigns** [comment]
Tested with current version and seems to work as expected. Output of test example:
[MD_KeySwitch example]
SINGLE PRESS
SINGLE PRESS
DOUBLE PRESS
DOUBLE PRESS
LONG PRESS
LONG PRESS
LONG PRESS
SINGLE PRESS  <- first of repeat sequence
SINGLE PRESS
SINGLE PRESS
SINGLE PRESS

**Comment by Extrunder** [comment]
Try to longpress without double pressing button before. Still not working for me (v1.4.1)

**Comment by MajicDesigns** [comment]
Double press not used or option disabled?

**Comment by Extrunder** [comment]
all options default (double press enabled, long press enabled, repeat enabled).

**Comment by MajicDesigns** [comment]
Still cannot make it happen. Logically, the FSM is reset after every sequence so what came before should not matter to the current keypress.
[MD_KeySwitch example]
SINGLE PRESS
LONG PRESS
SINGLE PRESS <- first of repeat pattern
REPEAT PRESS
REPEAT PRESS
REPEAT PRESS
REPEAT PRESS
SINGLE PRESS <- single press again
SINGLE PRESS
SINGLE PRESS
LONG PRESS
LONG PRESS
SINGLE PRESS <- first of repeat presses
REPEAT PRESS
REPEAT PRESS
REPEAT PRESS

**Comment by Extrunder** [comment]
Ok, let's sort it out together. I commented irrelevant code for this case...
Repeat and Long press are enabled together (by default)
```
case S_LPRESS:
    // 1 condition
    if (!b/*|| !bitRead(_enableFlags, REPEAT_ENABLE)*/) {
        k = /*bitRead(_enableFlags, LONGPRESS_ENABLE) ? */KS_LONGPRESS/* : KS_PRESS*/;
        _state = S_WAIT;
        break;
    }
case S_REPEAT:
    if (!b) {
        _state = S_IDLE; 
        break;
    }
    if ((millis() - _timeActive) < _timeRepeat) {
        break;
    }
    k = KS_REPEAT;
    _state = /*bitRead(_enableFlags, REPEAT_ENABLE) ? */S_REPEAT/* : S_WAIT*/;
    _timeActive = millis();
    break;
```
If I release button right after KS_LONGPRESS fire, then everything is ok.
But if  I hold button long enough to trigger KS_REPEAT then '1 condition' falsely and KS_LONGPRESS missing.

I hope this will help.

**Comment by MajicDesigns** [comment]
So if I read you correctly, you are expecting that LONGPRESS is returned instead of PRESS before the repeat presses? Is that a correct interpretation?

**Comment by Extrunder** [comment]
Yep. It seems expected and predictible result, if both repeat and longpress is enabled, rather than silently skip longpress event if user not count in mind time intervals for longpress.
This code fix problem (in S_LPRESS case).
```
} else if (bitRead(_enableFlags, REPEAT_ENABLE) && bitRead(_enableFlags, LONGPRESS_ENABLE)) {
    k = KS_LONGPRESS;
    _state = S_REPEAT;
    break;
}
```
it generates one longpress event before repeat

**Comment by MajicDesigns** [comment]
What you are describing as an "expected and predictable result" is not what most users would be expecting.

For example, on a keyboard, a key has a primary function that is accessed using a simple press. The key can have modifiers applied (say, shift, ctl or alt), which are equivalent to double or long press modifiers. However, when the user keeps the key pressed they expect that after a short delay they will get a repeat of the primary function (simple press) not a modified key press followed by repeat of the key press. How annoyed would you be if you pressed 'a' and after a while got 'Aaaaaaa' when it repeats?

If you need this type of functionality then I would suggest you make local modifications to the library for your applications.

**Comment by Extrunder** [comment]
We are talking about single button, not a whole bunch of keyboard keys with OS-specified behaviour.
User may disable longpress if it is not needed at all, right?
In (v1.4.1) there is no possibility to do longpress without timer in other hand (450ms longpress, 650ms repeat, hmmm... I have only 200ms to release key. OK. I can do it :). Of course I can disable repeat at all. But wait, if I need repeat and longpress flags enabled together, then only possible thing I can do is to use hand timer to simple longpress button. Also there is possible to tune timings, but, wait, I want things go faster! It simply is not user friendly.
With this simple fix there be expected result: PRESS, LONGPRESS, REPEAT, REPEAT, REPEAT... longpress will works everytime not obscured by repeat flag state.

Sure I already fixed all the stuff in my repo. Sorry, but I have not much time to argue. This is a good project and thank you for great job. It really help me to save time in development.
Good luck!
