### ISSUE TITLE
Add KS_REPEAT rather than repeatedly send KP_PRESS

### ISSUE THREAD

**Issue by Extrunder** [MajicDesigns/MD_KeySwitch#3]
It is not possible to handle difference between simple press and repeated press.

**Comment by MajicDesigns** [comment]
Please explain why this is desirable.

**Comment by MajicDesigns** [comment]
New method enableRepeatResult(bool) that will enable the retrurn of KS_RPTPRESS for repeat key presses. The first on the sequence will always be KS_PRESS and subsequent repeats KS_RPTPRESS.
Default option is for this to be off and all repeats are passed back as KS_PRESS (original behaviour).

**Comment by Extrunder** [comment]
For example I using single button to handle basic menu navigation:
- single press -> enter
- longpress -> esc (blocked by menu in value edit mode)
- repeat -> cyclic change value
Without separate KP_REPEAT it is not possible to differ basic press from repeated event.
